#define             VAR						1
#define             CONST					2
#define             INT			 			3
#define             IF						4
#define             ELSE					5
#define             WHILE					6
#define             PRINT					8
#define             READ					9
#define             ID						10
#define             ENTERO					11
#define             CADENA					12
#define             SEPARADOR				13
#define             COMMA					14
#define             PLUSOP					15
#define             MINUSOP				16
#define             MULOP					17
#define             DIVOP					18
#define             ASSIGNOP				19
#define             LPAREN					20
#define             RPAREN					21
#define             LLLAVE					22
#define             RLLAVE					23
#define             INTERR					24
#define             DPUNTOS				25
#define				ERROR_TOKEN				-2